config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'stories#index'
  resources :stories, only: [:index, :create, :show]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/archetype.rb
class Archetype
  ALL = {
    artist: { 
      name: 'The Artist',
      description: 'With her head in the clouds, and a paintbrush in hand, the artist archetype is the most likely to dream up truly creative solutions in technology. With a penchant for design and a flair for music, the artist is often found seeking inspiration in art galleries, or working on a photography project. You can expect this girl to invent technology that supports the artistic community: designers, film-makers and more. ',
      full_image_name: 'characters/artist.png',
      face_image_name: 'thumbnails/artist.png'
    },
    explorer: { 
      name: 'The Explorer',
      description: "Bravely breaking down barriers, and fearlessly going outside her comfort zone, the adventurer is always on the hunt for new frontiers in technology. Never one to be fenced in, she’s ready to get up and go where no tech girl has gone before. Her pioneering spirit is an inspiration to her fellow tech girls, and she’s always ready for the next big adventure!",
      full_image_name: 'characters/explorer.png',
      face_image_name: 'thumbnails/explorer.png'
    },
    daredevil: { 
      name: 'The Daredevil',
      description: "Never tell the the daredevil something can't be done! She just won't believe it. The daredevil is always ready to push the boundaries and use technology in new and innovative ways to come up with answers nobody thought possible! Dressed most often in sharp black, with a few piercings and maybe even a tattoo, the daredevil might look a little wild but underneath it all she's a tech maverick with a heart of gold.",
      full_image_name: 'characters/daredevil.png',
      face_image_name: 'thumbnails/daredevil.png'
    },
    tomboy: { 
      name: 'The Tomboy',
      description: "Who says girls have to wear pink and play with dolls? Not this gal! The tomboy doesn't mind getting her hands dirty, and can mix it with the boys just as easily as the girls. She's sporty and light-hearted, and loves to take things apart to see how they work before putting them back together again in her own way! Usually found in jeans, t-shirts and cool sneakers, the tomboy is always ready to leap into action.",
      full_image_name: 'characters/tomboy.png',
      face_image_name: 'thumbnails/tomboy.png'
    },
    sophisticate: { 
      name: 'The Sophisticate',
      description: "This girl is far from precious, but she does love to display her femininity and fashion sense - she uses her style to express herself and she doesn't see why she can't be fashion-forward AND a lover of technology at the same time! The sophisticate likes high-end fashion, 6 inch heels and technology that looks hot and works like a dream. She can see her ICT career taking her all over the world, flying first class naturally!",
      full_image_name: 'characters/sophisticate.png',
      face_image_name: 'thumbnails/sophisticate.png'
    }
  }

  def self.with_key(key:)
    ALL[key]
  end

  def self.keys
    ALL.keys
  end

  def self.form_collection
    collection = []
    Archetype::ALL.each_pair { |k, v| collection << [v[:name], k.to_s]} 
    collection
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  validates :body, presence: true

  belongs_to :super_hero
  accepts_nested_attributes_for :super_hero

  after_create :create_map_point

  # after_destroy :remove_map_point

  private

  def create_map_point
    MapAdapter.create_point(super_hero.postcode)
  end

  # def remove_map_point
  #   MapAdapter.remove_point(super_hero.postcode)
  # end
end

app/models/super_hero.rb
class SuperHero < ActiveRecord::Base
  validates :name, :super_power, :postcode,
            :age, :year_at_school, :email, presence: true

  validates :name, :email, uniqueness: true

  has_one :story
 
  def archetype_data
    @data ||= Archetype.with_key(key: archetype.to_sym)
    @data
  end
end

app/models/twilio_sms.rb
class TwilioSms
  include ActiveModel::Model
  attr_reader :to, :from, :client, :superhero_name
  validates_presence_of :to, :from

  def initialize(args)
    @to             = args[:to]
    @from           = args[:from]
    @superhero_name = args[:superhero_name]
  end

  def send
    setup_twilio_client
    client.account.messages.create(to, from, body)
  end

  private

  def setup_twilio_client
    account_sid = Rails.application.secrets.twilio_account_sid
    auth_token  = Rails.application.secrets.twilio_auth_token
    @client     = Twilio::REST::Client.new(account_sid, auth_token)
  end

  def body
    "Welcome #{superhero_name} to the #techgirls sisterhood!
    Thank you for sharing your story. It has been posted to http://bit.ly/1vZr3wd"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    if terms = params[:search]
      @stories = Story.basic_search(terms).order(created_at: :desc)
    else
      @stories = Story.order(created_at: :desc)
    end
  end

  def show
    @story = Story.includes(:super_hero).find(params[:id])
  end

  def create
    @story = Story.new(story_attributes)

    if @story.save
      send_email(@story.super_hero.name, @story.super_hero.email)
      redirect_to root_path, notice: 'Story created successfully'
    else
      render :index, status: 400
    end
  end

  private

  def story_attributes
    params.require(:story).permit(:body,
      super_hero_attributes: [:name, :super_power, :postcode, :age, :year_at_school, :email, :phone, :archetype] )
  end

  def send_email(to_name, to_email)
    ::EmailSender.send_email(
      from_name:  'Tech Girls are Superheroes',
      from_email: 'techgirlsaresuperheroes@gmail.com',
      to_name:    to_name,
      to_email:   to_email,
      subject:    'Your story has been posted',
      html:       render_to_string(layout: false,template: 'stories/email.html.haml')
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    = viewport_meta_tag
    %title= content_for?(:title) ? yield(:title) : "Tech Girls Community"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"

  %body
    %nav.navbar.navbar-default.navbar-fixed-top(role="navigation")
      .container
        .navbar-header
          %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to('Tech Girls Community', root_path, class: 'navbar-brand')

        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.navbar-left
            %li= modal_toggle 'Write a Story', dialog: '#create_story'
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Search', '#search'

    .container
      .row
        .col-md-12
          = bootstrap_flash
          = yield
    #search
      %button.close{type: "button"} ×
      =form_tag root_path, method: "get" do
        %input{placeholder: "type keyword(s) here", type: "search", value: "", name: "search"}/
        %button.btn.btn-primary{type: "submit"} Search

    #create_story.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog"}
      .modal-dialog.modal-lg
        .modal-content
          .modal-header
            %button.close{"data-dismiss" => "modal", type: "button"}
              %span{"aria-hidden" => "true"} ×
              %span.sr-only Close
            %h4#myModalLabel.modal-title Write a story

          .modal-body.clearfix
            - if @story
              :javascript
                $('.modal').modal('show');
            - else
              - @story = Story.new

            - @story.build_super_hero unless @story.super_hero.present?

            = simple_form_for(@story, url: stories_path, method: :post, html: { class: 'form-vertical' }) do |f|
              = f.simple_fields_for :super_hero do |shf|
                .col-md-6.clearfix
                  = shf.input :name, label: "What's your superhero name?"
                  = shf.input :archetype, as: :radio_buttons, collection: Archetype.form_collection,
                    wrapper: :vertical_radio_and_checkboxes, label: 'What tech girl are you?'
                  = shf.input :postcode
                  = shf.input :year_at_school
                .col-md-6.clearfix
                  = shf.input :super_power, label: "What's your super power?"
                  = shf.input :age
                  = shf.input :email
                  = shf.input :phone
              .col-md-12.clearfix
                = f.input :body, as: :text, label: 'Why do I love technology'

              .action.col-md-12.clearfix
                = f.button :submit, 'Create Story', class: 'btn btn-primary'
    %footer
      .text-center
        %p= "&copy; Tech Girls #{Date.today.year}".html_safe

app/views/stories/email.html.haml
%h1= "Hi #{@story.super_hero.name}!"

%p Welcome to the #techgirls sisterhood! Thank you for sharing your story, it has now been posted and you can view it here:

%p= link_to story_url(@story)

%p Please encourage your friends to share their #techgirl stories too!

%p Order your free Tech Girls are Superheroes Book at www.techgirlsaresuperheroes.org

%p Follow us on social media to keep in touch with #techgirls news:

%ul
  %li= link_to 'Facebook - Tech Girls are Superheroes', 'https://www.facebook.com/Techgirlsaresuperheroes'
  %li= link_to 'Twitter - @TGAsuperheroes',             'https://twitter.com/TGAsuperheroes'
  %li= link_to 'Instagram - @techgirlsaresuperheroes',  'http://instagram.com/techgirlsaresuperheroes'

%p Go #techgirls from all of us here at the Tech Girls Movement!

app/views/stories/index.html.haml
.stories
  - if @stories.present?
    #wallmessages.qa-message-list
      .container
        .row
          - @stories.each do |story|
            .message-item{ id: dom_id(story) }
              .message-inner
                .message-head.clearfix
                  .avatar.pull-left
                    = link_to(story_path(story)) do
                      = image_tag(story.super_hero.archetype_data[:face_image_name])
                  .user-detail
                    %h5.handle
                      = "#{ story.super_hero.name } | #{ story.super_hero.super_power }"
                    .post-meta
                      .asker-meta
                        %span.qa-message-what
                        %span.qa-message-when
                          %span.qa-message-when-data
                            = story.created_at.to_s(:long)
                .qa-message-content
                  = story.body
  - else
    %p
      There were no stories entered yet.

.map
  -# %iframe.bigsky{src:'http://bigsky.io/maps/69a5807'}
  %iframe.bigsky{src:'http://bigsky.io/maps/d30242b'}

app/views/stories/show.html.haml
.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      .box
        .box-icon
          %span
            = image_tag @story.super_hero.archetype_data[:face_image_name]
        .info
          %h4.text-center
            = "#{ @story.super_hero.name } | #{ @story.super_hero.super_power }"
          %p= @story.body